sudo: false
language: cpp
branches:
  only:
    - master

jobs:
  include:
    - os: linux
      dist: xenial
      sudo: require
      compiler: g++
      addons:
        apt:
          sources:
            - sourceline: ppa:ubuntu-toolchain-r/test
            - sourceline: ppa:beineri/opt-qt-5.12.6-xenial
          packages:
            - g++-7
            - git
      env:
        - APPIMAGE="true"
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - os: linux
      dist: xenial
      sudo: require
      services: docker
      env: WEBASM="true"
    - os: osx
      osx_image: xcode11.0
      compiler: clang
      env:
        - DMG="true"
        - MATRIX_EVAL="COMPILER=clang++"

before_install:
    - if [ -z "${GITHUB_TOKEN}" ]; then
        export GITHUB_TOKEN="${github_token}";
        echo "Add GITHUB_TOKEN to your Travis Settings Environment Varable with a value from Github Settings Developer Personal access tolkens";
      fi
    - if [ -z "${GITHUB_USERNAME}" ]; then
        echo "Add GITHUB_USERNAME to your Travis Settings Environment Varable with your Github User Name, the first one in the path to github.";
      fi
    - if [ -z "${GITHUB_EMAIL}" ]; then
        echo "Add GITHUB_EMAIL to your Travis Settings Environment Varable with your Github email address.";
      fi
    - if [ -z "${REPO_SLUG}" ]; then
        export REPO_SLUG="Light-Wizzard/galaxy-calculator";
        echo "Add REPO_SLUG to your Travis Settings Environment Varable with the path from your Github project, User-Name/Project-Name";
      fi
    - if [ -z "${BIN}" ]; then
        export BIN="Galaxy-Calculator";
        echo "Add BIN to your Travis Settings Environment Varable with a value from Github x";
      fi
    - if [ -z "${QTV}" ]; then
        export QTV="qt512";
        echo "Add QTV to your Travis Settings Environment Varable with the version of Qt you want to use from beineri repo, qt512";
      fi
    - if [ -z "${QT_WASM_VER}" ]; then
        export QT_WASM_VER="5.13_latest";
        echo "Add QT_WASM_VER to your Travis Settings Environment Varable with the version of Qt WASM, 5.13_latest";
      fi

install:
    - if [ ! -z "${APPIMAGE}" ]; then 
        sudo apt update -qq; 
        echo "Install qt libraries for Linux";
        sudo apt install build-essential ${QTV}base ${QTV}quickcontrols ${QTV}quickcontrols2 ${QTV}graphicaleffects ${QTV}svg ${QTV}scxml libgl1-mesa-dev; 
        export ARTIFACT="${BIN}-travis-x86_64.AppImage";
        export ARTIFACT_ZSYNC="${BIN}-travis-x86_64.AppImage.zsync";
      fi
    - if [ ! -z "${DMG}" ]; then 
        echo "Download last version of Qt with brew for Mac";
        brew update > /dev/null; 
        brew install qt5; 
        chmod -R 755 /usr/local/opt/qt5/*; 
        export QTDIR="/usr/local/opt/qt5"; export PATH="${QTDIR}/bin:$PATH"; export ARTIFACT="${BIN}*.dmg"; 
      fi
      
script:
    - eval "${MATRIX_EVAL}"
    - if [ ! -z "${APPIMAGE}" ]; then
        echo "Load Qt env Make Linux AppImage in /home/travis/build/[secure]/${BIN}";
        source /opt/qt*/bin/qt*-env.sh;
        echo "Build project";
        mkdir build && cd build;
        qmake ..;
        make;
        echo "Create deploy folder=/home/travis/build/[secure]/${BIN}/build/deploy/build/deploy";
        mkdir -p deploy/; mkdir -p deploy/usr/;  mkdir -p deploy/usr/bin/; mkdir -p deploy/usr/share/;
        mkdir -p deploy/usr/share/applications/; mkdir -p deploy/usr/doc/; mkdir -p deploy/usr/share/doc/libc6/;
        cp -v /usr/share/doc/libc6/copyright deploy/usr/share/doc/libc6/copyright;
        echo "Copy files over";
        rsync -avz ../usr deploy/
        ls -lh deploy/usr/share/applications/;
        echo "Moving executable";
        ls -lh;
        mv -v "$BIN" deploy/usr/bin/; 
        echo "Donwload and run linuxdeployqt continuous..."; 
        ls -lh deploy/usr/bin/;
        cd deploy/;
        ls -lh;
        echo "Donwload and run linuxdeployqt continuous...";
        wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage";
        chmod a+x linuxdeployqt-continuous-x86_64.AppImage;
        unset QTDIR; unset QT_PLUGIN_PATH ; unset LD_LIBRARY_PATH;
        OUTPUT="${BIN}";
        export VERSION=travis;
        ./linuxdeployqt-continuous-x86_64.AppImage "usr/bin/${BIN}" -extra-plugins=iconengines,imageformats -verbose=2 -qmldir=../../qml -appimage;
        echo "Completed LinuxDeployQt";
        cd ../;
        ls -lh;
      fi
    - if [ ! -z "${DMG}" ]; then
        echo "Build project for Mac in /home/travis/build/[secure]/${BIN}";
        mkdir build && cd build;
        qmake ..;
        make;
        echo "Run macdeployqt";
        macdeployqt "${BIN}.app/" -qmldir=../qml -dmg;
        find . | grep dmg;
      fi
    - if [ ! -z "${WEBASM}" ]; then
        echo "Build WEBASM in /home/travis/build/[secure]/${BIN}";
        git remote set-url origin https://${GITHUB_TOKEN}@github.com/${GITHUB_USERNAME}/${BIN};
        git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*";
        git fetch --all;
        git config --global user.name "${GITHUB_USERNAME}";
        git config --global user.email "${GITHUB_EMAIL}";
        echo "WEBASM make build folder and run docker";
        mkdir build;
        docker run --rm -v "${PWD}:/project/source" -v "${PWD}/build:/project/build" maukalinow/qtwasm_builder:${QT_WASM_VER};
        rm -rf build/{Makefile,*.o,*.cpp};
        git checkout --track origin/gh-pages;
        mv -v build/* .;
        rm -rf build;
        sudo mv -v "${BIN}.html" index.html;
        echo "Created WEBASM";
        ls -lh;
        git add --all;
        git commit -sm "Update WebAssembly";
      fi    

after_success:
    - if [ "${TRAVIS_PULL_REQUEST}" != false ] || [ "${TRAVIS_BRANCH}" != "master" ]; then
        echo "This is not the master branch, no deploy will be done";
        travis_terminate 0;
      fi
    - wget -c https://raw.githubusercontent.com/${GITHUB_USERNAME}/${BIN}/master/deploy/upload.sh;
    - if [ ! -z "${APPIMAGE}" ]; then bash ./upload.sh deploy/${ARTIFACT}; bash ./upload.sh deploy/${ARTIFACT_ZSYNC}; fi
    - if [ ! -z "${DMG}" ]; then bash ./upload.sh $ARTIFACT; fi
    - if [ ! -z "${WEBASM}" ]; then git push origin gh-pages; fi
