language: cpp
branches:
  only:
    - master
env:
  global:
    - BIN=galaxy-calculator

# I get a warning without them, and two extra jobs with them, comment out.
#os:
#  - linux
#  - osx

#dist: xenial

jobs:
  include:
    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - sourceline: ppa:ubuntu-toolchain-r/test
            - sourceline: ppa:beineri/opt-qt-5.12.6-xenial
          packages:
            - g++-7
            - git
      env:
        - APPIMAGE="true"
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - os: linux
      dist: xenial
      services: docker
      env: WEBASM="true"
    - os: osx
      osx_image: xcode11.0
      compiler: clang
      env:
        - DMG="true"
        - MATRIX_EVAL="COMPILER=clang++"
        
install:
    - if [ ! -z "${APPIMAGE}" ]; then 
        export QTV=qt512; 
        sudo apt update -qq; 
        echo "Install qt libraries for Linux";
        sudo apt install build-essential ${QTV}base ${QTV}quickcontrols ${QTV}quickcontrols2 ${QTV}graphicaleffects ${QTV}svg ${QTV}scxml libgl1-mesa-dev; 
        export ARTIFACT="$BIN*.AppImage";
      fi
    - if [ ! -z "${DMG}" ]; then 
        echo "Download last version of Qt with brew for Mac";
        brew update > /dev/null; 
        brew install qt5; 
        chmod -R 755 /usr/local/opt/qt5/*; 
        export QTDIR="/usr/local/opt/qt5"; export PATH="${QTDIR}/bin:$PATH"; export ARTIFACT="${BIN}*.dmg"; 
      fi
      
script:
    - export GITHUB_TOKEN="${github_token}"
    - eval "${MATRIX_EVAL}"
    - if [ ! -z "${APPIMAGE}" ]; then 
        echo "Load Qt env Make Linux AppImage in ${PWD}";
        source /opt/qt*/bin/qt*-env.sh;
        echo "Build project in folder=/home/travis/build/[secure]/galaxy-calculator/build/deploy/build"; 
        mkdir build && cd build; 
        qmake ..; make; 
        echo "Create deploy folder=/home/travis/build/[secure]/galaxy-calculator/build/deploy/build/deploy";
        mkdir deploy; 
        cp "../deploy/${BIN}.png" deploy/;
        cp "../deploy/${BIN}.desktop" deploy/; 
        ls;
        mv "$BIN" deploy/; 
        echo "Donwload and run linuxdeployqt continuous..."; 
        wget -c "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage";
        chmod a+x linuxdeployqt*.AppImage; 
        unset QTDIR; unset QT_PLUGIN_PATH ; unset LD_LIBRARY_PATH;
        mkdir -p deploy/usr/share/doc/libc6/; cp /usr/share/doc/libc6/copyright deploy/usr/share/doc/libc6/copyright;
        ./linuxdeployqt*.AppImage "deploy/${BIN}.desktop" -bundle-non-qt-libs -extra-plugins=iconengines,imageformats -verbose=2 -qmldir=../qml -appimage; 
        echo "LinuxDeployQt finished AppImage in build/deploy";
        mv Galaxy-Calculator-*.AppImage "${BIN}.AppImage"; 
        mv Galaxy-Calculator-*.AppImage.zsync "${BIN}.AppImage.zsync"; 
        echo "Renamed Galaxy-Calculator-*-x86_64.AppImage and Galaxy-Calculator-*-x86_64.AppImage.zsync too ${BIN}";
        ls;
        echo "Created Linux ${BIN}.AppImage and ${BIN}.AppImage.zsync";
      fi    
    - if [ ! -z "${DMG}" ]; then 
        echo "Build project for Mac in ${PWD}";
        mkdir -p build && cd build;
        mkdir -p build/deploy;
        qmake ..; make;
        echo "Run macdeployqt"; 
        macdeployqt "${BIN}.app/" -qmldir=../qml -dmg; 
        mv "${BIN}.dmg" deploy/;
        ls deploy/*;
        echo "Created Mac ${BIN}.dmg";
      fi
    - if [ ! -z "${WEBASM}" ]; then 
        echo "Build WEBASM in ${PWD}";
        git remote set-url origin https://${GITHUB_TOKEN}@github.com/Light-Wizzard/galaxy-calculator;
        git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"; 
        git fetch --all;
        git config --global user.name "Light-Wizzard";
        git config --global user.email "thelightwizzard@gmail.com"; 
        git tag continuous
        echo "WEBASM make build folder and run docker";
        mkdir -p build;
        mkdir -p build/deploy;
        docker run --rm -v "${PWD}:/project/source" -v "${PWD}/build:/project/build" maukalinow/qtwasm_builder:5.13_latest;
        rm -rf build/{Makefile,*.o,*.cpp}; 
        git checkout --track origin/gh-pages; 
        sudo mv "${BIN}.html" build/deploy/index.html;
        echo "WebAssembly Renamed ${BIN}.html too index.html";
        cd build/deploy/;
        ls;
        git add index.html;
        git commit -sm "Update WebAssembly"; 
        git push --tags;
      fi

before_deploy:
    - git config --local user.name "Light-Wizzard"
    - git config --local user.email "thelightwizzard@gmail.com"
    - git tag continuous

deploy:
    provider: releases
    api_key:
        secure: "${GITHUB_TOKEN}"
    file:
        - "${BIN}.AppImage"
        - "${BIN}.AppImage.zsync"
        - "index.html"
        - "${BIN}.dmg"
    skip_cleanup: true
    on:
        repo: Light-Wizzard/galaxy-calculator
        tags: true

# End of File

