sudo: false
language: cpp
branches:
  only:
    - master

jobs:
  include:
    - os: linux
      dist: xenial
      sudo: require
      compiler: gcc
      addons:
        apt:
          sources:
            - sourceline: ppa:ubuntu-toolchain-r/test
            - sourceline: ppa:beineri/opt-qt-5.12.6-xenial
          packages:
            - binutils
            - g++-7
            - libgl1-mesa-dev
            - libxkbcommon-x11-0
            - zlib1g-dev
            - libzstd-dev
            - p7zip-full  
            - g++-7
            - git
      env:
        - APPIMAGE="true"
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
        - QT_BEINERI_VERSION="qt512"

    - os: linux
      dist: xenial
      sudo: require
      services: docker
      env: 
        - WEBASM="true"
        - QT_WASM_VER="5.13_latest"
    - os: osx
      osx_image: xcode11.0
      compiler: clang
      env:
        - DMG="true"
        - MATRIX_EVAL="COMPILER=clang++"

before_install:
    - if [ -z "${BIN_PRO_RES_NAME+x}" ]; then echo -e "${WARNING_COLOR}Add BIN_PRO_RES_NAME to your Travis Settings Environment Variable with a value from Github value for Binary, pro, and resource Name ${NC}"; fi

install:
    - if [ -n "${DMG}" ]; then 
        echo "Download last version of Qt with brew for Mac";
        brew update > /dev/null; 
        brew install qt5; 
        chmod -R 755 /usr/local/opt/qt5/*; 
        export QTDIR="/usr/local/opt/qt5"; export PATH="${QTDIR}/bin:$PATH"; 
      fi
      
script:
    - eval "${MATRIX_EVAL}"
    - if [ -n "${APPIMAGE}" ]; then 
        declare -g ARTIFACT_APPIMAGE;
        declare -g ARTIFACT_ZSYNC;
        declare -g ARTIFACT_QIF;
        source tools/build-with-qmake.sh "$QT_BEINERI_VERSION"; 
      fi
    - if [ -n "${DMG}" ]; then
        echo "Build project for Mac in /home/travis/build/[secure]/${BIN_PRO_RES_NAME}";
        mkdir build && cd build;
        qmake ..;
        make;
        echo "Run macdeployqt";
        macdeployqt "${BIN_PRO_RES_NAME}.app/" -qmldir=../qml -dmg;
        find . | grep dmg;
        export ARTIFACT="${BIN_PRO_RES_NAME}.dmg"; 
      fi
    - if [ -n "${WEBASM}" ]; then
        echo "Build WEBASM in /home/travis/build/[secure]/${BIN_PRO_RES_NAME}";
        git config --global user.email "${GITHUB_EMAIL}"  >/dev/null 2>&1;
        git config --global user.name "${GITHUB_USERNAME}"  >/dev/null 2>&1;
        git remote set-url origin https://${GITHUB_TOKEN}@github.com/${GITHUB_USERNAME}/${BIN_PRO_RES_NAME};
        git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*";
        git fetch --all;
        echo "WEBASM make build folder and run docker";
        mkdir -p build;
        docker run --rm -v "${PWD}:/project/source" -v "${PWD}/build:/project/build" "maukalinow/qtwasm_builder:${QT_WASM_VER}";
        sudo rm -rf build/{Makefile,*.o,*.cpp};
        git checkout --track origin/gh-pages;
        sudo mv -v build/* .;
        sudo rm -rf build;
        sudo mv -v "${BIN_PRO_RES_NAME}.html" index.html;
        echo "Created WEBASM";
        ls -lh;
        git add --all;
        git commit -sm "Update WebAssembly";
      fi    

after_success:
    - if [ "${TRAVIS_PULL_REQUEST}" != false ] || [ "${TRAVIS_BRANCH}" != "master" ]; then
        echo "This is not the master branch, no deploy will be done"; travis_terminate 0;
      fi
    - wget -c https://raw.githubusercontent.com/${GITHUB_USERNAME}/${BIN_PRO_RES_NAME}/master/tools/upload.sh;
    - if [ -n "${APPIMAGE}" ] && [ -f "${ARTIFACT_APPIMAGE}" ];   then bash ./upload.sh "${ARTIFACT_APPIMAGE}"; fi
    - if [ -n "${APPIMAGE}" ] && [ -f "${ARTIFACT_ZSYNC}" ];      then bash ./upload.sh "${ARTIFACT_ZSYNC}"; fi
    - if [ -n "${APPIMAGE}" ] && [ -f "${ARTIFACT_QIF}" ];        then bash ./upload.sh "${ARTIFACT_QIF}"; fi
    - if [ -n "${DMG}" ]; then bash ./upload.sh "$ARTIFACT"; fi
    - if [ -n "${WEBASM}" ]; then git push origin gh-pages; fi
    
