sudo: false
language: cpp
branches:
  only:
    - master

jobs:
  include:
    - os: linux
      dist: xenial
      sudo: require
      compiler: g++
      addons:
        apt:
          sources:
            - sourceline: ppa:ubuntu-toolchain-r/test
            - sourceline: ppa:beineri/opt-qt-5.12.6-xenial
          packages:
            - g++-7
            - git
      env:
        - APPIMAGE="true"
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - os: linux
      dist: xenial
      sudo: require
      services: docker
      env: WEBASM="true"
    - os: osx
      osx_image: xcode11.0
      compiler: clang
      env:
        - DMG="true"
        - MATRIX_EVAL="COMPILER=clang++"
        
install:
    - if [ ! -z "${APPIMAGE}" ]; then 
        sudo apt update -qq; 
        echo "Install qt libraries for Linux";
        sudo apt install build-essential ${QTV}base ${QTV}quickcontrols ${QTV}quickcontrols2 ${QTV}graphicaleffects ${QTV}svg ${QTV}scxml libgl1-mesa-dev; 
        export ARTIFACT="${BIN}-travis-x86_64.AppImage";
        export ARTIFACT_ZSYNC="${BIN}-travis-x86_64.AppImage.zsync";
      fi
    - if [ ! -z "${DMG}" ]; then 
        echo "Download last version of Qt with brew for Mac";
        brew update > /dev/null; 
        brew install qt5; 
        chmod -R 755 /usr/local/opt/qt5/*; 
        export QTDIR="/usr/local/opt/qt5"; export PATH="${QTDIR}/bin:$PATH"; export ARTIFACT="${BIN}*.dmg"; 
      fi
      
script:
    - eval "${MATRIX_EVAL}"
    - if [ ! -z "${APPIMAGE}" ]; then
        export BIN_NAME="Galaxy-Calculator";
        export BIN="Galaxy-Calculator";
        echo "Load Qt env Make Linux AppImage in /home/travis/build/[secure]/${BIN}";
        source /opt/qt*/bin/qt*-env.sh;
        echo "Build project";
        mkdir build && cd build;
        qmake ..;
        make;
        echo "Create deploy folder=/home/travis/build/[secure]/${BIN_NAME}/build/deploy/build/deploy";
        mkdir -p deploy/; mkdir -p deploy/usr/; mkdir -p deploy/usr/bin/; mkdir -p deploy/usr/share/; mkdir -p deploy/usr/share/applications/;
        echo "Copy files over";
        cp -v "../usr/share/applications/${BIN_NAME}.png"     deploy/usr/share/applications/;
        cp -v "../usr/share/applications/${BIN_NAME}.desktop" deploy/usr/share/applications/; 
        ls -lh deploy/usr/share/applications/;
        ls -lh;
        mv -v "$BIN_NAME" deploy/usr/bin/; 
        echo "Donwload and run linuxdeployqt continuous..."; 
        ls -lh deploy/usr/bin/;
        wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage";
        chmod a+x linuxdeployqt-continuous-x86_64.AppImage;
        unset QTDIR; unset QT_PLUGIN_PATH ; unset LD_LIBRARY_PATH;
        mkdir -p deploy/usr/share/doc/libc6/; cp -v /usr/share/doc/libc6/copyright deploy/usr/share/doc/libc6/copyright;
        OUTPUT="${BIN}";
        export VERSION=travis;
        ./linuxdeployqt*.AppImage "deploy/usr/share/applications/${BIN}" -bundle-non-qt-libs -extra-plugins=iconengines,imageformats -verbose=2 -qmldir=../qml -appimage; 
        echo "Completed LinuxDeployQt";
        ls -lh;
      fi
    - if [ ! -z "${DMG}" ]; then
        export BIN_NAME="${BIN}";
        echo "Build project for Mac in /home/travis/build/[secure]/${BIN_NAME}";
        mkdir build && cd build;
        qmake ..;
        make;
        echo "Run macdeployqt";
        macdeployqt "${BIN_NAME}.app/" -qmldir=../qml -dmg; 
        find . | grep dmg;
      fi
    - if [ ! -z "${WEBASM}" ]; then
        export BIN_NAME="${BIN}";
        echo "Build WEBASM in /home/travis/build/[secure]/${BIN_NAME}";
        git remote set-url origin https://${GITHUB_TOKEN}@github.com/${GITHUB_USERNAME}/${BIN_NAME};
        git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*";
        git fetch --all;
        git config --global user.name "${GITHUB_USERNAME}";
        git config --global user.email "${GITHUB_EMAIL}";
        echo "WEBASM make build folder and run docker";
        mkdir build;
        docker run --rm -v "${PWD}:/project/source" -v "${PWD}/build:/project/build" maukalinow/qtwasm_builder:${QT_WASM_VER};
        rm -rf build/{Makefile,*.o,*.cpp};
        git checkout --track origin/gh-pages;
        mv -v build/* .;
        rm -rf build;
        sudo mv -v "${BIN_NAME}.html" index.html;
        echo "Created WEBASM";
        ls -lh;
        git add --all;
        git commit -sm "Update WebAssembly";
      fi    

after_success:
    - if [ "${TRAVIS_PULL_REQUEST}" != false ] || [ "${TRAVIS_BRANCH}" != "master" ]; then
        echo "This is not the master branch, no deploy will be done";
        travis_terminate 0;
      fi
    - wget -c https://raw.githubusercontent.com/${GITHUB_USERNAME}/${BIN}/master/deploy/upload.sh;
    - if [ ! -z "${APPIMAGE}" ]; then bash ./upload.sh ${ARTIFACT}; bash ./upload.sh ${ARTIFACT_ZSYNC}; fi
    - if [ ! -z "${DMG}" ]; then bash ./upload.sh $ARTIFACT; fi
    - if [ ! -z "${WEBASM}" ]; then git push origin gh-pages; fi

